# === users_controller
#
# @author Moisés Reis
# @added 11/25/2025
# @package *Meta*
# @description This controller manages all **User** accounts in the application,
#              handling listing, viewing, creation, and updating of user information.
#              It is typically restricted to administrative users. The explanations are in the present simple tense.
# @category *Controller*
#
# Usage:: - *[What]* This code block controls the management of user data, defining how user accounts are listed and modified.
#         - *[How]* It uses search functionality via **Ransack** to filter users and standard CRUD actions to interact with the **User** model.
#         - *[Why]* It provides a necessary administrative interface for managing the users who access the application.
#
# Attributes:: - *@user* @object - The specific user record being handled (show, edit, update).
#              - *@users* @collection - The filtered and paginated list of user records for the index view.
#
class UsersController < ApplicationController

  # Explanation:: This command confirms that a user is successfully logged into
  #               the system before allowing access to any actions within this controller.
  before_action :authenticate_user!

  # == index
  #
  # @author Moisés Reis
  # @category *Read*
  #
  # Read:: This action retrieves and displays a paginated and searchable list of users based on the current user's role.
  #        It displays all users for administrators and prevents data retrieval for standard users.
  #
  # Attributes:: - *@q* - The search object generated by the **Ransack** gem.
  #              - *@users* - The filtered and paginated collection of **User** records.
  #
  def index

    # Explanation:: This variable stores the total number of records found in the database.
    #               It allows the user to see exactly how many items exist in the list.
    @total_items = User.count

    # Explanation:: This checks if the currently logged-in user possesses the administrative role.
    #               It assumes the User model has a method `admin?` to check the role.
    if current_user.admin?

      # Explanation:: This initializes the search object using the **Ransack** gem,
      #               applying any search criteria passed by the administrator.
      @q = User.ransack(params[:q])

      # Explanation:: This executes the search query, ensures distinct results, and then
      #               divides the complete list of users into pages of 17 items.
      @users = @q.result(distinct: true).page(params[:page]).per(14)

    else

      # Explanation:: If the user is not an administrator, the search object is set to a
      #               search on an empty collection, ensuring no user data is retrieved.
      @q = User.none.ransack(params[:q])

      # Explanation:: The resulting user list is explicitly set to an empty collection.
      #               This prevents any user information from being displayed to standard users.
      @users = User.none

      # Explanation:: This executes the search query, ensures distinct results, and then
      #               divides the complete list of users into pages of 16 items.
      @users = @q.result(distinct: true).page(params[:page]).per(16)
    end
  end

  # == show
  #
  # @author Moisés Reis
  # @category *Read*
  #
  # Read:: This action finds and displays the detailed information for a single user account.
  #        It uses the ID provided in the web address to locate the specific **User** record.
  #
  # Attributes:: - *@user* - The single **User** object found by the ID parameter.
  #
  def show
    @user = User.find(params[:id])
  end

  # == new
  #
  # @author Moisés Reis
  # @category *Read*
  #
  # Read:: This action creates a new, blank **User** object.
  #        This empty object is used by the form to gather input from the administrator for a new user creation.
  #
  # Attributes:: - *@user* - A new, unsaved **User** instance.
  #
  def new
    @user = User.new
  end

  # == create
  #
  # @author Moisés Reis
  # @category *Create*
  #
  # Create:: This action attempts to save a new user record to the database using the submitted form data.
  #          If successful, it redirects to the new user's show page; otherwise, it displays the form again with errors.
  #
  # Attributes:: - *@user* - The new **User** object created from the sanitized parameters.
  #
  def create

    # Explanation:: This initializes a new **User** object using only the safe, permitted
    #               attributes received from the submission form.
    @user = User.new(user_params)

    # Explanation:: This checks if the new user object successfully passes all database
    #               validations and saves the record, confirming successful account creation.
    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # == destroy
  #
  # @author Moisés Reis
  # @category *Delete*
  #
  # Delete:: This action removes an existing user record from the database.
  #          It first finds the specific user by ID and then attempts to destroy the record.
  #
  # Attributes:: - *@user* - The existing **User** object to be deleted.
  #
  def destroy

    # Explanation:: This finds the existing **User** object from the database using the
    #               ID provided in the web address parameters, ensuring the correct user is targeted.
    @user = User.find(params[:id])

    # Explanation:: This permanently removes the user record from the database.
    @user.destroy

    # Explanation:: This redirects the administrator to the list of all users (`index` page)
    #               after the deletion is successfully completed.
    redirect_to users_url, notice: "User was successfully destroyed.", status: :see_other
  end

  # == edit
  #
  # @author Moisés Reis
  # @category *Read*
  #
  # Read:: This action finds and prepares the existing user's data for editing.
  #        It loads the data into the form so the administrator can see the current values before making changes.
  #
  # Attributes:: - *@user* - The existing **User** object loaded by the ID parameter.
  #
  def edit
    @user = User.find(params[:id])
  end

  # == update
  #
  # @author Moisés Reis
  # @category *Update*
  #
  # Update:: This action attempts to modify an existing user record with new data submitted from the edit form.
  #          If successful, it redirects to the user's show page; otherwise, it displays the form again with errors.
  #
  # Attributes:: - *@user* - The existing **User** object to be updated.
  #
  def update

    # Explanation:: This finds the existing **User** object from the database using the
    #               ID provided in the web address parameters.
    @user = User.find(params[:id])

    # Explanation:: This attempts to update the user record with the new, permitted attributes,
    #               checking for successful validation and database save.
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  # == user_params
  #
  # @author Moisés Reis
  # @category *Security*
  #
  # Security:: This private method sanitizes all incoming data from the user form.
  #            It ensures that only specifically permitted fields like `first_name`,
  #            `last_name`, `email`, and `role` are allowed to be saved to the database.
  #
  # Attributes:: - *params* - The raw data hash received from the user form submission.
  #
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :role,
      :password,
      :password_confirmation
    )
  end
end