# === fund_investment.rb
#
# Description:: Tracks the relationship between a specific portfolio and an investment fund.
#               This model manages the balances of quotas held and the financial value
#               invested by a user within a particular fund.
#
# Usage:: - *What* - Represents a specific holding of a fund within a user's collection.
#         - *How* - It calculates market values, returns, and validates allocation limits.
#         - *Why* - To provide a consolidated view of fund performance and ownership.
#
# Attributes:: - *@portfolio_id* [Integer] - The ID of the associated +Portfolio+.
#              - *@investment_fund_id* [Integer] - The ID of the associated +InvestmentFund+.
#              - *@total_invested_value* [Decimal] - The total amount of money put into the fund.
#              - *@total_quotas_held* [Decimal] - The number of shares or quotas currently owned.
#              - *@percentage_allocation* [Decimal] - The target weight of this fund in the portfolio.
#
# View:: - +FundInvestmentsView+
#
# Notes:: References other models such as +Application+, +Redemption+, and +PerformanceHistory+.
#
class FundInvestment < ApplicationRecord

  # Explain what this line does in two or three lines.
  # Establishes the ownership link to a specific investment portfolio.
  belongs_to :portfolio

  # Explain what this line does in two or three lines.
  # Connects this investment record to the global investment fund definitions.
  belongs_to :investment_fund

  # Explain what this line does in two or three lines.
  # Manages the collection of purchase records associated with this fund.
  has_many :applications, dependent: :destroy

  # Explain what this line does in two or three lines.
  # Tracks all withdrawal activities and removes them if the investment is deleted.
  has_many :redemptions, dependent: :destroy

  # Explain what this line does in two or three lines.
  # Stores periodic performance metrics generated by background calculation jobs.
  has_many :performance_histories, dependent: :destroy

  # =============================================================
  #                        Configuration
  # =============================================================

  validates :portfolio_id, presence: true
  validates :investment_fund_id, presence: true

  validates :total_invested_value, presence: true,
            numericality: { greater_than_or_equal_to: 0 }

  validates :total_quotas_held, presence: true,
            numericality: { greater_than_or_equal_to: 0 }

  validates :percentage_allocation, presence: true, numericality: {
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 100
  }

  validates :investment_fund_id, uniqueness: { scope: :portfolio_id }

  validate :portfolio_allocation_within_limits

  # Explain what this line does in two or three lines.
  # Provides a virtual attribute to bypass allocation checks during bulk updates.
  attr_accessor :skip_allocation_validation

  # =============================================================
  #                           Scopes
  # =============================================================

  # Filters investments that currently hold a positive balance of quotas.
  scope :active, -> { where("total_quotas_held > 0") }

  # Organizes the investment list based on the highest percentage of allocation.
  scope :by_allocation, -> { order(percentage_allocation: :desc) }

  # Determines visibility based on ownership or shared portfolio permissions.
  scope :accessible_to, ->(user) {
    if user.admin?
      all
    else
      joins(:portfolio)
        .joins("LEFT JOIN user_portfolio_permissions ON user_portfolio_permissions.portfolio_id = portfolios.id")
        .where(
          "portfolios.user_id = ? OR user_portfolio_permissions.user_id = ?",
          user.id, user.id
        )
        .distinct
    end
  }

  # Limits results to investments residing in portfolios the user can read.
  scope :readable_by, ->(user) {
    joins(:portfolio)
      .where(portfolios: { id: Portfolio.readable_by(user).select(:id) })
      .distinct
  }

  # Retrieves investments that belong directly to the specified user.
  scope :owned_by, ->(user) {
    joins(:portfolio).where(portfolios: { user_id: user.id })
  }

  # Finds investments shared with the user through third-party permissions.
  scope :with_permissions_for, ->(user) {
    joins(portfolio: :user_portfolio_permissions)
      .where(user_portfolio_permissions: { user_id: user.id })
      .where.not(portfolios: { user_id: user.id })
  }

  # =============================================================
  #                        Public Methods
  # =============================================================

  # == update_balances!
  # @author Moisés Reis
  #
  # Updates total quotas and invested value atomically to avoid race conditions.
  # It uses a database lock to ensure data integrity during concurrent updates.
  #
  # Parameters::
  # - *quotas_delta* - The change in the number of quotas held.
  # - *value_delta* - The change in the total invested financial value.
  #
  # Returns::
  # - Returns true if the record was successfully saved after the update.
  def update_balances!(quotas_delta:, value_delta:)
    with_lock do
      self.skip_allocation_validation = true
      self.total_quotas_held = (total_quotas_held || 0) + quotas_delta
      self.total_invested_value = (total_invested_value || 0) + value_delta
      save!
    end
  end

  # == current_market_value
  # @author Moisés Reis
  #
  # Calculates the current financial value of held quotas based on a specific date.
  # This serves as a real-time valuation of the user's position in the fund.
  #
  # Parameters::
  # - *date* - The reference date used to look up the fund's quota price.
  #
  # Returns::
  # - The market value as a BigDecimal or zero if no data is available.
  def current_market_value(date = Date.current)
    quota = investment_fund.quota_value_on(date)
    return BigDecimal("0") unless quota && total_quotas_held

    value = total_quotas_held * quota
    value < BigDecimal("1") ? BigDecimal("0") : value
  end

  # == current_market_value_on
  # @author Moisés Reis
  #
  # Reconstructs the historical market value by replaying transactions up to a date.
  # It calculates the quota balance on that specific day and prices it accordingly.
  #
  # Parameters::
  # - *date* - The historical point in time for which to calculate valuation.
  #
  # Returns::
  # - The historical financial market value as a BigDecimal.
  def current_market_value_on(date)
    quota = investment_fund.quota_value_on(date)
    return BigDecimal("0") unless quota

    quotas = applications.where("cotization_date <= ?", date).sum(:number_of_quotas) -
             redemptions.where("cotization_date <= ?", date).sum(:redeemed_quotas)

    BigDecimal(quotas.to_s) * quota
  end

  # == unrealized_gain_loss
  # @author Moisés Reis
  #
  # Calculates the difference between the current market value and the amount invested.
  # This represents the potential profit or loss if the fund were sold immediately.
  #
  # Returns::
  # - The calculated gain or loss amount as a BigDecimal.
  def unrealized_gain_loss(date = Date.current)
    current_market_value(date) - total_invested_value
  end

  # == return_percentage
  # @author Moisés Reis
  #
  # Computes the simple percentage return relative to the total cost basis.
  # It provides a quick snapshot of performance without considering cash flow timing.
  #
  # Returns::
  # - The return percentage expressed as a BigDecimal.
  def return_percentage(date = Date.current)
    return BigDecimal("0") if total_invested_value.zero?

    (unrealized_gain_loss(date) / total_invested_value) * 100
  end

  # == total_applications
  # @author Moisés Reis
  #
  # Calculates the gross sum of all financial contributions made to this fund.
  #
  # Returns::
  # - The total amount applied to the fund as a BigDecimal.
  def total_applications
    BigDecimal(applications.sum(:financial_value).to_s)
  end

  # == total_redemptions
  # @author Moisés Reis
  #
  # Sums the total liquid value of all withdrawals performed by the user.
  #
  # Returns::
  # - The total amount redeemed from the fund as a BigDecimal.
  def total_redemptions
    BigDecimal(redemptions.sum(:redeemed_liquid_value).to_s)
  end

  # == total_gain
  # @author Moisés Reis
  #
  # Determines the absolute profit or loss since the very first application.
  # It factors in both current holdings and past redemptions against total cost.
  #
  # Parameters::
  # - *date* - The reference date used for current valuation pricing.
  #
  # Returns::
  # - The total financial gain or loss as a BigDecimal.
  def total_gain(date = Date.current)
    total_redemptions + current_market_value_on(date) - total_applications
  end

  # == monthly_gain_at
  # @author Moisés Reis
  #
  # Retrieves stored earnings for a specific month from the performance history.
  #
  # Parameters::
  # - *period_end_date* - The end date of the month to look up.
  #
  # Returns::
  # - The earnings amount or nil if the record does not exist.
  def monthly_gain_at(period_end_date)
    performance_histories.find_by(period: period_end_date)&.earnings
  end

  # == monthly_return_at
  # @author Moisés Reis
  #
  # Returns the stored return percentage for a specific monthly period.
  #
  # Parameters::
  # - *period_end_date* - The date marking the end of the calculation period.
  #
  # Returns::
  # - The return percentage as a BigDecimal or nil.
  def monthly_return_at(period_end_date)
    performance_histories.find_by(period: period_end_date)&.monthly_return
  end

  # == initial_date
  # @author Moisés Reis
  #
  # Identifies the date of the very first transaction for this investment.
  #
  # Returns::
  # - The earliest cotization date as a Date object.
  def initial_date
    applications.minimum(:cotization_date)
  end

  # == initial_invested_value
  # @author Moisés Reis
  #
  # Sums the capital invested on the very first day of the investment lifecycle.
  #
  # Returns::
  # - The opening capital value as a BigDecimal.
  def initial_invested_value
    return BigDecimal("0") unless initial_date
    BigDecimal(applications.where(cotization_date: initial_date).sum(:financial_value).to_s)
  end

  # == period_applications
  # @author Moisés Reis
  #
  # Calculates the sum of all money invested after the initial opening date.
  #
  # Returns::
  # - The subsequent investment inflows as a BigDecimal.
  def period_applications
    return BigDecimal("0") unless initial_date
    BigDecimal(applications.where("cotization_date > ?", initial_date).sum(:financial_value).to_s)
  end

  # == net_movement_on
  #
  # @author Moisés Reis
  #
  # Calculates the net financial flow of an investment during a specific month.
  # It subtracts the total value of redemptions from the total value of applications for the period.
  #
  # Parameters::
  # - *date* - The reference date that determines the target month for the calculation.
  #
  # Returns::
  # - The net financial movement as a BigDecimal.

  def net_movement_on(date)
    start_date = date.to_date.beginning_of_month

    end_date = date.to_date.end_of_month

    apps = applications.where(request_date: start_date..end_date).sum(:financial_value)

    reds = redemptions.where(request_date: start_date..end_date).sum(:redeemed_liquid_value)

    BigDecimal(apps.to_s) - BigDecimal(reds.to_s)
  end

  # == dietz_weighted_cash_flow
  # @author Moisés Reis
  #
  # Calculates the denominator for Modified Dietz return based on cash flow timing.
  # It weights inflows and outflows by the amount of time they were in the fund.
  #
  # Parameters::
  # - *end_date* - The closing date of the calculation period.
  #
  # Returns::
  # - The weighted cash flow value used for performance formulas.
  def dietz_weighted_cash_flow(end_date = Date.current)
    start_date = initial_date
    return nil unless start_date

    total_days = BigDecimal((end_date - start_date).to_i.to_s)
    return nil if total_days <= 0

    weighted = BigDecimal("0")

    applications.each do |app|
      next unless app.cotization_date && app.financial_value
      days_remaining = (end_date - app.cotization_date).to_i
      next if days_remaining < 0
      weight = BigDecimal(days_remaining.to_s) / total_days
      weighted += BigDecimal(app.financial_value.to_s) * weight
    end

    redemptions.each do |red|
      next unless red.cotization_date && red.redeemed_liquid_value
      days_remaining = (end_date - red.cotization_date).to_i
      next if days_remaining < 0
      weight = BigDecimal(days_remaining.to_s) / total_days
      weighted -= BigDecimal(red.redeemed_liquid_value.to_s) * weight
    end

    weighted
  end

  # == latest_monthly_return
  # @author Moisés Reis
  #
  # Retrieves the return percentage from the most recent performance history record.
  #
  # Returns::
  # - The most recent monthly return as a BigDecimal.
  def latest_monthly_return
    performance_histories.order(period: :desc).first&.monthly_return
  end

  # == period_return_percentage
  # @author Moisés Reis
  #
  # Computes the cumulative return since inception using the Modified Dietz method.
  # This provides a more accurate performance metric than simple snapshots.
  #
  # Parameters::
  # - *date* - The end date for the historical performance window.
  #
  # Returns::
  # - The cumulative return percentage as a BigDecimal.
  def period_return_percentage(date = Date.current)
    gain = total_gain(date)
    weighted = dietz_weighted_cash_flow(date)

    return BigDecimal("0") if weighted.nil? || weighted.zero?

    (gain / weighted) * 100
  end

  # == self.ransackable_attributes
  # @author Moisés Reis
  #
  # Whitelists attributes for searchability via the Ransack gem.
  #
  # Returns::
  # - An array of searchable field names.
  def self.ransackable_attributes(auth_object = nil)
    %w[
      created_at
      id
      investment_fund_id
      percentage_allocation
      portfolio_id
      total_invested_value
      total_quotas_held
      updated_at
    ]
  end

  # == self.ransackable_associations
  # @author Moisés Reis
  #
  # Permits searches across related models such as funds and applications.
  #
  # Returns::
  # - An array of association names available for searching.
  def self.ransackable_associations(auth_object = nil)
    %w[
      applications
      investment_fund
      performance_histories
      portfolio
      redemptions
    ]
  end

  # =============================================================
  #                        Private Methods
  # =============================================================

  private

  # == portfolio_allocation_within_limits
  # @author Moisés Reis
  #
  # Validates that the sum of fund allocations does not exceed 100% of the portfolio.
  def portfolio_allocation_within_limits
    return if skip_allocation_validation
    return unless portfolio && percentage_allocation

    total_allocation = portfolio.fund_investments
                                .where.not(id: id)
                                .sum(:percentage_allocation) + percentage_allocation

    if total_allocation > 100
      errors.add(:percentage_allocation, "it exceeds the portfolio's total allocation limit of 100%")
    end
  end
end